# Generated by Django 6.0 on 2025-12-19 15:26

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        default="بدون اسم",
                        max_length=128,
                        null=True,
                        verbose_name="نام",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        default="بدون اسم",
                        max_length=128,
                        null=True,
                        verbose_name="نام خانوادگی",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_user", "ابرکاربر"),
                            ("coach", "مربی"),
                            ("athlete", "ورزشکار"),
                        ],
                        default="athlete",
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("m", "مرد"), ("f", "زن")],
                        max_length=10,
                        null=True,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(9),
                            django.core.validators.MaxLengthValidator(11),
                        ],
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/profiles/",
                        verbose_name="تصویر",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="ابرکاربر"),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="کارمند")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "ordering": ["-created_at"],
            },
        ),
    ]
