# Generated by Django 6.0 on 2025-12-19 16:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.PositiveIntegerField(verbose_name="مبلغ (تومان)")),
                ("paid_at", models.DateField(verbose_name="تاریخ پرداخت")),
                (
                    "month_label",
                    models.CharField(
                        choices=[
                            ("farvardin", "فروردین"),
                            ("ordibehesht", "اردیبهشت"),
                            ("khordad", "خرداد"),
                            ("tir", "تیر"),
                            ("mordad", "مرداد"),
                            ("shahrivar", "شهریور"),
                            ("mehr", "مهر"),
                            ("aban", "آبان"),
                            ("azar", "آذر"),
                            ("dey", "دی"),
                            ("bahman", "بهمن"),
                            ("esfand", "اسفند"),
                        ],
                        max_length=12,
                        verbose_name="ماه مربوطه",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "پرداخت شده"), ("due", "بدهکار")],
                        default="paid",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "athlete"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ورزشکار",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "ordering": ["-paid_at"],
            },
        ),
    ]
