# Generated by Django 6.0 on 2025-12-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentmodel",
            options={"verbose_name": "پرداخت", "verbose_name_plural": "پرداخت\u200cها"},
        ),
        migrations.RemoveField(
            model_name="paymentmodel",
            name="paid_at",
        ),
    ]
